version: "2.1"

services: 

  telegraf:
    build: .
    pid: "host"
    network_mode: "host"
    privileged: true
    labels:
      io.resin.features.balena-socket: '1'
    environment:
      - INFLUX_URL=http://influxdb.hjemme.nett:8086
      - INFLUX_DB=telegraf
